"""Add votes table and fields

Revision ID: 57766eddda9e
Revises: 6f91442f0680
Create Date: 2025-04-28 01:28:16.341749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57766eddda9e'
down_revision: Union[str, None] = '6f91442f0680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('upvotes', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('downvotes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'downvotes')
    op.drop_column('posts', 'upvotes')
    # ### end Alembic commands ###
